USE Bioware
GO
/*ALTER TABLE OrderDetails WITH CHECK
ADD CONSTRAINT FK_Inventory# FOREIGN KEY(Inventory#) REFERENCES Products(ID)
ON UPDATE CASCADE
GO
ALTER TABLE OrderDetails WITH CHECK
ADD CONSTRAINT FK_OrderID FOREIGN KEY(OrderID) REFERENCES Orders(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_RetailerID FOREIGN KEY(RetailerID) REFERENCES Retailers(RetailerID)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_LocationID FOREIGN KEY(LocationID) REFERENCES Location(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_CustomerID FOREIGN KEY(CustomerID) REFERENCES Customers(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Customers WITH CHECK
ADD CONSTRAINT FK_Zipcode FOREIGN KEY(Zipcode) REFERENCES Customers(Zipcode)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_CustomerID FOREIGN KEY(CustomerID) REFERENCES Customers(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Retailers WITH CHECK
ADD CONSTRAINT FK_Zipcode FOREIGN KEY(Zipcode) REFERENCES Zipcode(Zipcode)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE Customers
ALTER COLUMN Zipcode varchar(10) NOT NULL
ALTER TABLE Customers WITH CHECK
ADD CONSTRAINT FK_Zipcode FOREIGN KEY(Zipcode) REFERENCES Zipcode(Zipcode)
ON UPDATE CASCADE
ALTER TABLE Retailers
ALTER COLUMN Zipcode varchar(10) NOT NULL
ALTER TABLE Retailers WITH CHECK
ADD CONSTRAINT FK_RetailerZipcode FOREIGN KEY(Zipcode) REFERENCES Zipcode(Zipcode)
ALTER TABLE OrderDetails
ALTER COLUMN Inventory# int NOT NULL
ALTER TABLE OrderDetails WITH CHECK
ADD CONSTRAINT FK_Inventory# FOREIGN KEY(Inventory#) REFERENCES Products(ID)
ON UPDATE CASCADE*/
